<?php

/**
 * @file
 * Hook implementations for dfs_obio_tour.
 */

/**
 * Implements hook_page_attachments().
 */
function dfs_obio_tour_page_attachments(array &$attachments) {
  $user = \Drupal::currentUser();
  $lift_enabled = FALSE;
  if (\Drupal::moduleHandler()->moduleExists('acquia_lift')) {
    $path_context = \Drupal::service('acquia_lift.service.context.path_context');
    $lift_enabled = $path_context->shouldAttach();
  }
  $attachments['#attached']['library'][] = 'dfs_obio_tour/main';
  $attachments['#attached']['drupalSettings']['dfs_obio_tour'] = [
    'uid' => $user->id() ?: '',
    'email' => $user->getEmail() ?: '',
    'username' => $user->getAccountName() ?: '',
    'lift_enabled' => $lift_enabled,
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function dfs_obio_tour_library_info_alter(&$libraries, $extension) {
  if ($extension === 'dfs_obio_tour') {
    $api_key = \Drupal::config('dfs_obio_tour.settings')->get('api_key');
    $definition = reset($libraries['inlinemanual']['js']);
    $url = str_replace('API_KEY', $api_key, key($libraries['inlinemanual']['js']));
    $libraries['inlinemanual']['js'] = [$url => $definition];
  }
}
